#pragma once
const float BLOCK_SIZE = 0.1;
const int CHUNK_WIDTH = 16; // Must be of 2^n
const int CHUNK_HEIGHT = 100;
const int CHUNK_HM_WIDTH = CHUNK_WIDTH +1;
const int CHUNK_HM_SIZE = CHUNK_HM_WIDTH * CHUNK_HM_WIDTH;
const int CHUNK_SIZE = CHUNK_WIDTH * CHUNK_WIDTH * CHUNK_HEIGHT;
const float CHUNK_UNIT_WIDTH = CHUNK_WIDTH * BLOCK_SIZE;

const int HEIGHTMAP_CHUNK_WIDTH = 8; // Must be of 2^n
const int HEIGHTMAP_BLOCK_WIDTH = (HEIGHTMAP_CHUNK_WIDTH * CHUNK_WIDTH) + 1;
const int HEIGHTMAP_SIZE = HEIGHTMAP_BLOCK_WIDTH * HEIGHTMAP_BLOCK_WIDTH;

const int MAX_TERRAIN_GEN_HEIGHT = 80;
const int MIN_TERRAIN_GEN_HEIGHT = 20;
const int HEIGHTMAP_BORDER_BLEND_LENGTH = 15;
